export const seatLayout = {
    "1": [
        { "category": "seater", "is_available": true, "is_sleeper": false, "position": 0, "price": 80, "seat_id": "3", "type": "nseat" },
        { "category": "seater", "is_available": false, "is_sleeper": false, "position": 0, "price": 0, "seat_id": "50466870532481007048", "type": "bseat" },
        { "category": "seater", "is_available": true, "is_sleeper": false, "position": 0, "price": 80, "seat_id": "13", "type": "rseat" },
        { "category": "seater", "is_available": true, "is_sleeper": false, "position": 0, "price": 80, "seat_id": "18", "type": "nseat" },
        { "category": "seater", "is_available": true, "is_sleeper": false, "position": 0, "price": 80, "seat_id": "23", "type": "nseat" }, { "category": "seater", "is_available": true, "is_sleeper": false, "position": 0, "price": 80, "seat_id": "28", "type": "nseat" }, { "category": "seater", "is_available": true, "is_sleeper": false, "position": 0, "price": 80, "seat_id": "33", "type": "nseat" }, { "category": "seater", "is_available": true, "is_sleeper": false, "position": 0, "price": 80, "seat_id": "36", "type": "nseat" }, { "category": "seater", "is_available": true, "is_sleeper": false, "position": 0, "price": 80, "seat_id": "42", "type": "nseat" }
    ],
    "2": [
        { "category": "seater", "is_available": true, "is_sleeper": false, "position": 30, "price": 80, "seat_id": "2", "type": "nseat" },
        { "category": "seater", "is_available": false, "is_sleeper": false, "position": 30, "price": 0, "seat_id": "50466870532481007047", "type": "bseat" },
        { "category": "seater", "is_available": true, "is_sleeper": false, "position": 30, "price": 80, "seat_id": "12", "type": "rseat" },
        { "category": "seater", "is_available": true, "is_sleeper": false, "position": 30, "price": 80, "seat_id": "17", "type": "nseat" },
        { "category": "seater", "is_available": true, "is_sleeper": false, "position": 30, "price": 80, "seat_id": "22", "type": "nseat" },
        { "category": "seater", "is_available": true, "is_sleeper": false, "position": 30, "price": 80, "seat_id": "27", "type": "nseat" },
        { "category": "seater", "is_available": true, "is_sleeper": false, "position": 30, "price": 80, "seat_id": "32", "type": "nseat" },
        { "category": "seater", "is_available": true, "is_sleeper": false, "position": 30, "price": 80, "seat_id": "35", "type": "nseat" },
        { "category": "seater", "is_available": true, "is_sleeper": false, "position": 30, "price": 80, "seat_id": "41", "type": "nseat" }], "3": [{ "category": "seater", "is_available": true, "is_sleeper": false, "position": 60, "price": 80, "seat_id": "1", "type": "nseat" }, {
            "category": "seater", "is_available":
                false, "is_sleeper": false, "position": 60, "price": 0, "seat_id": "50466870532481007046", "type": "bseat"
        }, { "category": "seater", "is_available": true, "is_sleeper": false, "position": 60, "price": 80, "seat_id": "11", "type": "rseat" }, { "category": "seater", "is_available": true, "is_sleeper": false, "position": 60, "price": 80, "seat_id": "16", "type": "nseat" }, { "category": "seater", "is_available": true, "is_sleeper": false, "position": 60, "price": 80, "seat_id": "21", "type": "nseat" }, { "category": "seater", "is_available": true, "is_sleeper": false, "position": 60, "price": 80, "seat_id": "26", "type": "nseat" }, { "category": "seater", "is_available": true, "is_sleeper": false, "position": 60, "price": 80, "seat_id": "31", "type": "nseat" }, { "category": "seater", "is_available": true, "is_sleeper": false, "position": 60, "price": 80, "seat_id": "34", "type": "nseat" }, { "category": "seater", "is_available": true, "is_sleeper": false, "position": 60, "price": 80, "seat_id": "40", "type": "nseat" }], "4": [{ "category": "seater", "is_available": true, "is_sleeper": false, "position": 90, "price": 80, "seat_id": "39", "type": "nseat" }], "5": [{ "category": "seater", "is_available": false, "is_sleeper": false, "position": 120, "price": 0, "seat_id": "50466870532481007045", "type": "bseat" }, { "category": "seater", "is_available": true, "is_sleeper": false, "position": 120, "price": 80, "seat_id": "10", "type": "rseat" }, { "category": "seater", "is_available": true, "is_sleeper": false, "position": 120, "price": 80, "seat_id": "15", "type": "rseat" }, { "category": "seater", "is_available": true, "is_sleeper": false, "position": 120, "price": 80, "seat_id": "20", "type": "nseat" }, { "category": "seater", "is_available": true, "is_sleeper": false, "position": 120, "price": 80, "seat_id": "25", "type": "nseat" }, { "category": "seater", "is_available": true, "is_sleeper": false, "position": 120, "price": 80, "seat_id": "30", "type": "nseat" }, {
            "category": "seater", "is_available": true, "is_sleeper": false, "position": 120, "price": 80, "seat_id": "38",
            "type": "nseat"
        }], "6": [{ "category": "seater", "is_available": false, "is_sleeper": false, "position": 150, "price": 0, "seat_id": "50466870532481007044", "type": "bseat" }, { "category": "seater", "is_available": true, "is_sleeper": false, "position": 150, "price": 80, "seat_id": "9", "type": "rseat" }, { "category": "seater", "is_available": false, "is_sleeper": false, "position": 150, "price": 0, "seat_id": "504668705324810070414", "type": "bseat" }, { "category": "seater", "is_available": true, "is_sleeper": false, "position": 150, "price": 80, "seat_id": "19", "type": "nseat" }, { "category": "seater", "is_available": true, "is_sleeper": false, "position": 150, "price": 80, "seat_id": "24", "type": "nseat" }, { "category": "seater", "is_available": true, "is_sleeper": false, "position": 150, "price": 80, "seat_id": "29", "type": "nseat" }, {
            "category": "seater", "is_available": true, "is_sleeper": false, "position": 150, "price": 80, "seat_id": "37",
            "type": "nseat"
        }]
}